# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS build
WORKDIR /app

# Install dependencies and build the project
COPY package.json tsconfig.json ./
COPY src ./src

# Install all dependencies ignoring scripts
RUN npm install --ignore-scripts

# Build the TypeScript project
RUN npm run build

FROM node:lts-alpine
WORKDIR /app

# Copy built files
COPY --from=build /app/dist ./dist
COPY package.json ./

# Install only production dependencies
RUN npm install --production --ignore-scripts

EXPOSE 3000

CMD ["node", "dist/index.js"]
