# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install pnpm globally because project uses pnpm in scripts
RUN npm install -g pnpm

# Copy package files
COPY package*.json ./
COPY pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile --ignore-scripts

# Copy all source code
COPY . .

# Build the project
RUN pnpm run build

# Expose port if necessary (not specified, but optional)
# EXPOSE 3000

# Command to run the server
CMD [ "npm", "start" ]
